# Generated by Django 6.0.4 on 2026-04-18 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_code', models.CharField(editable=False, max_length=20, unique=True)),
                ('intent', models.CharField(max_length=50)),
                ('entities', models.JSONField()),
                ('risk_score', models.FloatField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], default='Pending', max_length=20)),
                ('steps', models.JSONField()),
                ('whatsapp_message', models.TextField()),
                ('email_message', models.TextField()),
                ('sms_message', models.TextField()),
                ('assigned_team', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
